### ISSUE TITLE
1.2 User Research

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#15]
### Task title ID: 1.2 User Research #15
**Task Description** 
To gather insights from stakeholders to ensure that the design and development of the system, meet the user needs and expectations effectively.
 
**Goals of the Task**
To create an outline of research objectives and key findings of the targeted user group.

**Completion criteria**

- Research objectives are met, and relevant insights are gathered.
- Research findings are effectively communicated to the project team and the stakeholders.
- User feedback and insights are integrated into the design and development process to improve the system.

**Allocated Time:** 2 Days
**Start/End Date:** 29 Aug 2023 - 1 Sep 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Collated insights and requirements from the stakeholder

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 29 Aug 2023 - 1 Sep 2023
