### ISSUE TITLE
1.5.5 Use Case Descriptions

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#16]
### Task title ID: 1.5.5 Use Case Descriptions #16
**Task Description** 
Describes each use case's user interaction with the system in all possible cases.
 
**Goals of the Task**
To ensure that project team and stakeholders are clear of all the possible interactions between the users and system in each use case.

**Completion criteria**
- All use case descriptions clearly list out all possible scenario flows.
- All use case descriptions are clearly identifiable by the name, description, primary actor involved, pre/post-conditions etc.
- All use case descriptions have been communicated and viewed by the project team and stakeholders.

**Allocated Time:** 2 Days
**Start/End Date:** 18 Sep 2023 - 20 Sep 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Listed out the various use case descriptions (actors , post-condition, pre-condition, alternative flows)

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 18 Sep 2023 - 20 Sep 2023
