### ISSUE TITLE
1.4 Product Description

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#21]
### Task title ID: 1.4 Product Description #21
**Task Description** 
To develop a comprehensive product description that effectively communicates the features, benefits, and value of the system to the stakeholders.

**Goals of the Task**

-  A well-documented report that effectively communicates the system's features, benefits, and value to the target audience.

**Completion criteria**

- The product description accurately represents the system's features and benefits. It should also be tailored to the stakeholder's needs
- The product description should be error-free and easy to understand

**Allocated Time:** 5
**Start/End Date:** 7 Sep 2023 - 12 Sep 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Written the product description in the report to the client. Discussed the validity of the description with the other teammates and got approved by Project Manager

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 7 Sep 2023 - 12 Sep 2023
