### ISSUE TITLE
1.4.1 Product Functionality

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#22]
### Task title ID: 1.4.1 Product Functionality #22
**Task Description** 
 To assess and validate the functionality of a product to ensure it meets the specified requirements works as intended, and aligns with user expectations.

**Goals of the Task**

- A comprehensive documentation of each function in the system.
- Identify the specific features that address the stakeholders' needs.

**Completion criteria**

- Documentation of functionalities should be clear to both team members and stakeholders.
- Product functionalities meet the specific requirements and user expectations.

**Allocated Time:** 2
**Start/End Date:** 7 Sep 2023 - 8 Sep 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Listed out all product functionality (User authentication, Dashboard, Job assignment/ rejection, etc).

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 7 Sep 2023 - 8 Sep 2023
