### ISSUE TITLE
1.6.1 Gantt Chart

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#23]
### Task title ID: 1.6.1 Gantt Chart #23
**Task Description** 
Create a comprehensive timeline, subdivided into individual phases, with all the necessary tasks and subtasks need to complete this project.
 
**Goals of the Task**
To ensure that project team and stakeholders are clear of timeline of the tasks required to accomplish this project.

**Completion criteria**
- The timeline plan is subdivided into the different phases of the waterfall model.
- The timeline plan consists of all possible tasks and subtasks within each phase which are necessary to complete this project.

**Allocated Time:** 1 Days
**Start/End Date:** 18 Sep 2023 - 19 Sep 2023
**Owner:** Cheryl
**Status:** Completed
**Priority:** High

**Comment by cherylthy** [comment]
Describe the work done in detail.
Create a gantt chart using waterfall model, added the different timelines and allocated task owner for each subtask.

Has this work been committed to the repo?
No

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 18 Sept 2023 - 19 Sep 2023
