### ISSUE TITLE
1.4.2 Assumptions and Dependencies

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#24]
### Task title ID: 1.4.2 Assumptions and Dependencies #24
**Task Description** 
  To identify, document, and evaluate the assumptions and dependencies that can impact a project's planning, execution, and successful completion.

**Goals of the Task**
Write up a comprehensive documentation of all identified assumptions and dependencies, including their description, status, and impact assessment.

**Completion criteria**
- All project assumptions and dependencies are identified and documented.
- Assumptions are validated, and dependencies are analyzed for their impact.
- Project stakeholders are informed about potential risks and dependencies.

**Allocated Time:** 2
**Start/End Date:** 7 Sep 2023 - 8 Sep 2023
**Owner:** Yu Fei
**Status:** Completed
**Priority:** High

**Comment by wongyufei1** [comment]
Describe the work done in detail.
Documented the list of assumptions for the application environment such as reliable internet etc. Documented the dependencies of the system which includes both external and internal system components as well as each component's features.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 7 Sep 2023 - 8 Sep 2023
