### ISSUE TITLE
1.6.2 Software Estimation

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#25]
### Task title ID: 1.6.2 Software Estimation #25
**Task Description** 
Estimate the size, duration and cost of this project using the given estimation models.
 
**Goals of the Task**
To ensure that project team and stakeholders are clear of the potential time and budget required to complete this project.

**Completion criteria**
- All use case points have been used to estimate the size of this project.
- The COCOMO Basic Model has been used to estimate the effort required to complete this project.

**Allocated Time:** 2 Days
**Start/End Date:** 20 Sep 2023 - 22 Sep 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** Medium

**Comment by y1xing** [comment]
Describe the work done in detail.
Calculated the unadjusted case weight, technical complexity factor, environment factor, use case point and estimated hours for this project. Resulting calculations have documented in the report. 

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 20 Sep 2023 - 22 Sep 2023
