### ISSUE TITLE
2.1 Architectural Design

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#28]
### Task title ID: 2.1 Architectural Design #28
**Task Description** 
Define the necessary components and interfaces to establish the system's structural and behavioral framework.
 
**Goals of the Task**
To provide the project team and stakeholders an overall image of the whole system, allowing them to understand and analyze the system.

**Completion criteria**
- All system components' structural and behavioral design are clearly defined.
- All relational structures between components are clearly defined.

**Allocated Time:** 32 Days
**Start/End Date:** 20 Sep 2023 - 22 Oct 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Completed the component diagram in digram.net while referring the class diagram which was referenced from the initial architecture diagram

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 20 Sep 2023 - 22 Oct 2023
