### ISSUE TITLE
1.5.1 UI Requirements

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#29]
### Task title ID: 1.5.1 UI Requirements #29
**Task Description** 
To specify and document the User Interface (UI) requirements that guide the design and development of the visual and interactive elements of a product, ensuring an intuitive and user-friendly user experience.

**Goals of the Task**

- Write a detailed document that outlines all UI requirements, including visual design, interaction guidelines, accessibility, and usability considerations.
- Create a wireframe using Figma to aid with visualization of the system.

**Completion criteria**

- All UI requirements are clear, comprehensive and aligned with user expectations.
- UI elements are specific to support a seamless and user-friendly experience.
- Accessibility and usability guidelines are integrated into the UI requirements.

**Allocated Time:** 2
**Start/End Date:** 11 Sep 2023 - 13 Sep 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Research on conventions for the UI and taken inspiration from similar websites. Listed out the full UI requirements and went through the project manager for approval

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 11 Sep 2023 - 13 Sep 2023
