### ISSUE TITLE
1.5.2 Functional Requirements

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#30]
### Task title ID: 1.5.2 Functional Requirements #29
**Task Description** 
To specify and document the functional requirements of a project, outlining the features, behaviors, and capabilities required to meet user needs and project objectives.

**Goals of the Task**
- Identify critical features and features that can be deferred to future releases if applicable.
- Write a detailed functional requirements document that outlines all functional requirements, including detailed descriptions specifying what the function should do as well as the acceptance criteria.

**Completion criteria**
- All functional requirements are well-documented, clear, and aligned with user expectations.
- Functional requirements are validated and verified with stakeholders to ensure accuracy.
- Functional requirements are prioritized based on business value and project goals.

**Allocated Time:** 2
**Start/End Date:** 11 Sep 2023 - 13 Sep 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
-

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Listed out the needed functional requirements such as dashboard, user authentication and authorization, job assignment, etc.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 11 Sep 2023 - 13 Sep 2023
