### ISSUE TITLE
1.5.3 Non-functional Requirements

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#31]
### Task title ID: 1.5.3 Non-functional Requirements #31
**Task Description** 
To specify and document the non-functional requirements of a project, outlining the qualities, constraints, and performance expectations to ensure the system's overall effectiveness and quality.

**Goals of the Task**
- Identify the non-functional requirements such as performance, safety and security etc.
- Write a detailed non-functional requirements document inclusive of detailed descriptions and measurement criteria.

**Completion criteria**

- All non-functional requirements are well-documented, clear, and aligned with project constraints, objectives, and quality standards.
- Non-functional requirements are validated and verified with stakeholders to ensure accuracy.

**Allocated Time:** 2
**Start/End Date:** 11 Sep 2023 - 13 Sep 2023
**Owner:** Derrick
**Status:** Completed
**Priority:** High

**Comment by DerrickLJH** [comment]
1. Describe the work done in detail.
Listed out all the non-functional requirements in the different categories (Generic, Performance, Safety and Security, Availability and Accessibility).

2. Has this work been committed to the repo? 
NA.

3. How does the work affect the completion deadline? 
NA.

4. Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

5. Start date and end date of the work done for this comment.
Start/End Date: 11 Sep 2023 - 13 Sep 2023
