### ISSUE TITLE
2.1.1 Overall System Architecture Diagram

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#32]
### Task title ID: 2.1.1 Overall System Architecture Diagram #32
**Task Description** 
Illustrates the ways the system interacts with the environment.
 
**Goals of the Task**
To provide the project team and stakeholders a high-level overview of the whole system.

**Completion criteria**
- All system and environmental components are clearly illustrated,
- All system interaction with environmental components is clearly defined.

**Allocated Time:** 2 Days
**Start/End Date:** 20 Sep 2023 - 22 Sep 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Illustrated the system interactions in diagram.net. Briefed team members on how the whole architecture works and got approval from PM

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 20 Sep 2023 - 22 Sep 2023
