### ISSUE TITLE
1.5.4 Use Case Diagram

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#33]
### Task title ID: 1.5.4 Use Case Diagram #33
**Task Description** 
To develop a visual representation of a system's functional requirements using a Use Case Diagram, which illustrates the interactions between users (actors) and the system to accomplish specific tasks and goals.

**Goals of the Task**
- Identify and list all actors (users and systems) that interact with the system.
- Create a visual representation of the system's functional requirements, illustrating actors, use cases, and their relationships.

**Completion criteria**
- The Use Case Diagram accurately represents the system's intended functionality and user interactions.
- Actors, use cases, and their relationships are clearly defined and organized.

**Allocated Time:** 1
**Start/End Date:** 13 Sep 2023 - 14 Sep 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Complete the Use Case Diagram for the relevant actor 

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 13 Sep 2023 - 14 Sep 2023
