### ISSUE TITLE
2.1.2 Component Diagram

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#34]
### Task title ID: 2.1.2 Component Diagram #34
**Task Description** 
Visualize the organization and relationships of components within the system, which includes components, interfaces, connectors and dependencies.
 
**Goals of the Task**
To provide a high-level overview of the components in the system to better communicate and collaborate with the project team on the design and development of the system.

**Completion criteria**
- All system components, interfaces, connectors and dependencies are clearly defined.
- All system components have been evaluated and optimized.

**Allocated Time:** 6 Days
**Start/End Date:** 16 Oct 2023 - 22 Oct 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Completed the component diagram in digram.net while referring the class diagram

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 16 Oct 2023 - 22 Oct 2023
