### ISSUE TITLE
2.2 Detailed Design

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#35]
### Task title ID: 2.2 Detailed Design #35
**Task Description** 
Refine and design individual modules and components, specifying their interfaces, data structures and algorithms.
 
**Goals of the Task**
To provide a comprehensive and unambiguous blueprint for the developers to follow during the development phase.

**Completion criteria**
- All system components' interfaces, data structures and algorithms are clearly defined.
- All system component designs have been evaluated and optimized.
- All system components have been communicated to the development team.

**Allocated Time:** 32 Days
**Start/End Date:** 25 Sep 2023 - 27 Oct 2023
**Owner:** Derrick
**Status:** Completed
**Priority:** High

**Comment by DerrickLJH** [comment]
Describe the work done in detail.
Fulfilled all completion criteria. 
Completed the class diagram, sequence diagram, and component diagram.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 28 Aug 2023 - 1 Sep 2023
