### ISSUE TITLE
2.2.1 Class Diagram

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#36]
### Task title ID: 2.2.1 Class Diagram #36
**Task Description** 
Design and visualize individual classes in each system component, specifying their attributes, methods, access levels, object-oriented relationships.
 
**Goals of the Task**
To provide a comprehensive and unambiguous blueprint for the developers to follow during the development phase.

**Completion criteria**
- All classes' attributes, methods, access levels, object-oriented relationships are clearly defined.
- All class designs have been evaluated and optimized.

**Allocated Time:** 18 Days
**Start/End Date:** 25 Sep 2023 - 13 Oct 2023
**Owner:** Derrick
**Status:** Completed
**Priority:** High

**Comment by DerrickLJH** [comment]
Describe the work done in detail.
Completed class diagram in diagrams.net
Completed designing and visualizing individual classes for each system component. Attributes, methods, access levels, and object-oriented relationships were clearly defined. The class designs were thoroughly evaluated and optimized for efficiency.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 28 Aug 2023 - 1 Sep 2023
