### ISSUE TITLE
2.2.2 Sequence Diagram

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#37]
### Task title ID: 2.2.2 Sequence Diagram #37
**Task Description** 
Illustrate the interactions and flow of messages between components over time for each specific functionality of the system.
 
**Goals of the Task**
- To evaluate and ensure that system design meets specified requirements.
- To aid in designing test cases for validating system behavior.

**Completion criteria**
- All functionality flows are clearly illustrated and defined.
- All functionality flows are evaluated and validated.

**Allocated Time:** 11 Days
**Start/End Date:** 16 Oct 2023 - 27 Oct 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Design and evaluate various test cases for the sequence diagram. Ensure that the flow of the sequence diagram is logical and follows closely to the class diagram.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 16 Oct 2023 - 27 Oct 2023
