### ISSUE TITLE
3.1 Prototyping Phase 1 (Admin System)

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#40]
### Task title ID: 3.1 Prototyping Phase 1 (Admin System) #40
**Task Description** 
To create a functional prototype of the admin system's core features, providing stakeholders with a tangible representation of the system's user interface and functionality.
 
**Goals of the Task**
Create an interactive prototype that demonstrates the core features of the admin system, including user interfaces, navigation, and basic functionality.

**Completion criteria**
- The prototype accurately represents the admin system's core features and user interfaces.
- The prototype aligns with project requirements and user expectations 

**Allocated Time:** 1 Days
**Start/End Date:** 30 Oct 2023 - 1 Nov 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Created functional prototype based on use case established

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No

Start date and end date of the work done for this comment.
Start/End Date: 30 Oct 2023 - 1 Nov 2023
