### ISSUE TITLE
3.1.1 QA Review Phase 1

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#41]
### Task title ID: 3.1.1 QA Review Phase 1 #41
**Task Description** 
To conduct a thorough quality assurance (QA) review of the Phase 1 admin system prototype, ensuring that it aligns with project requirements, design specifications, and usability standards.
 
**Goals of the Task**
Detailed report summarizing the results of the QA review including identified defects, usability findings, and recommendations for improvements.

**Completion criteria**
- The Phase 1 admin system prototype aligns with project requirements and design specifications.
- Identified defects and issues are documented and addressed.
- Usability and performance standards are met or improved through feedback and refinements.

**Allocated Time:** 2 Days
**Start/End Date:** 1 Nov 2023 - 3 Nov 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Conduct various test on quality assurance and ensure that the prototype is align with the requirements and specification.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 1 Nov 2023 - 3 Nov 2023
