### ISSUE TITLE
3.2 Prototyping Phase 2 (Manager System)

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#42]
### Task title ID: 3.2 Prototyping Phase 2 (Manager System) #42
**Task Description** 
To create a functional prototype of the manager system's core features, providing stakeholders with a tangible representation of the system's user interface and functionality.
 
**Goals of the Task**
Create an interactive prototype that demonstrates the core features of the manager system, including user interfaces, navigation, and basic functionality.

**Completion criteria**
- The prototype accurately represents the manager system's core features and user interfaces.
- The prototype aligns with project requirements and user expectations 

**Allocated Time:** 2 Days
**Start/End Date:** 3 Nov 2023 - 5 Nov 2023
**Owner:** Derrick
**Status:** Completed
**Priority:** High

**Comment by DerrickLJH** [comment]
Describe the work done in detail.
Created an interactive prototype that demonstrates the core features of the manager system, including user interfaces, navigation, and basic functionality.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 3 Nov 2023 - 5 Nov 2023
