### ISSUE TITLE
3.2.1 QA Review Phase 2

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#43]
### Task title ID: 3.2.1 QA Review Phase 2 #43
**Task Description** 
To conduct a thorough quality assurance (QA) review of the Phase 2 manager system prototype, ensuring that it aligns with project requirements, design specifications, and usability standards.
 
**Goals of the Task**
Detailed report summarizing the results of the QA review including identified defects, usability findings, and recommendations for improvements.

**Completion criteria**
- The Phase 2 manager system prototype aligns with project requirements and design specifications.
- Identified defects and issues are documented and addressed.
- Usability and performance standards are met or improved through feedback and refinements.

**Allocated Time:** 2 Days
**Start/End Date:** 6 Nov 2023 - 8 Nov 2023
**Owner:** Yi Xing
**Status:** Completed
**Priority:** High

**Comment by y1xing** [comment]
Describe the work done in detail.
Conducted a thorough quality assurance (QA) review of the Phase 2 manager system prototype, ensuring that it aligns with project requirements, design specifications, and usability standards.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 6 Nov 2023 - 8 Nov 2023
