### ISSUE TITLE
3.3 Prototyping Phase 3 (Cabin Crew System)

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#44]
### Task title ID: 3.3 Prototyping Phase 3 (Cabin Crew System) #44
**Task Description** 
To create a functional prototype of the cabin crew system's core features, providing stakeholders with a tangible representation of the system's user interface and functionality.
 
**Goals of the Task**
Create an interactive prototype that demonstrates the core features of the cabin crew system, including user interfaces, navigation, and basic functionality.

**Completion criteria**
- The prototype accurately represents the cabin crew system's core features and user interfaces.
- The prototype aligns with project requirements and user expectations 

**Allocated Time:** 2 Days
**Start/End Date:** 8 Nov 2023 - 10 Nov 2023
**Owner:** Yu Fei
**Status:** Completed
**Priority:** High

**Comment by wongyufei1** [comment]
Describe the work done in detail.
Completed the design and construction work of the wireframe of the Cabin Crew System in Figma.
Ensured that the functional and UI design fits the project requirements and use cases.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 8 Nov 2023 - 10 Nov 2023
