### ISSUE TITLE
4.1 Test Case Planning

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#46]
### Task title ID: 4.1 Test Case Planning #46
**Task Description** 
To create a comprehensive test case plan that outlines the strategy, scope, and approach for testing a software system, ensuring that all relevant scenarios and conditions are covered to validate the system's functionality and performance.
 
**Goals of the Task**
- Create a comprehensive document outlining the test case strategy, scope, design, and execution schedule.
- Detailed test case documents for each identified test scenario, including steps, inputs, expected outcomes, and traceability to requirements.

**Completion criteria**
- The test case plan is comprehensive and aligns with project requirements and objectives.
- Test cases are designed to cover critical and relevant scenarios.
-  The test case plan is followed, and defects are reported and resolved as per the plan.

**Allocated Time:** 2 Days
**Start/End Date:** 13 Nov 2023 - 15 Nov 2023
**Owner:** Isaac
**Status:** Backlog
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Created a test case plan which is aligned with the project's strategy, scope and approach to software testing. Ensure the various user-test cases and scenarios are extensively covered.
Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 13 Nov 2023 - 15 Nov 2023
