### ISSUE TITLE
4.2 White Box Testing

### ISSUE THREAD

**Issue by cherylthy** [wongyufei1/INF2001_P3-2#47]
### Task title ID: 4.2 White Box Testing #47
**Task Description** 
To conduct white box testing, with the goal of evaluating the internal logic, structure, and functionality of a software application's source code to identify defects and ensure code quality.
 
**Goals of the Task**
Create a comprehensive report containing the results of white box testing, including code coverage metrics, defect reports, and any performance or security findings.

**Completion criteria**
- Code components are thoroughly tested, and defects are identified and documented.
- Code coverage meets or exceeds the defined criteria.
- Code quality issues and vulnerabilities are addressed.
- Performance and security requirements are met

**Allocated Time:** 5 Days
**Start/End Date:** 16 Nov 2023 - 21 Nov 2023
**Owner:** Derrick
**Status:** Backlog
**Priority:** High

**Comment by DerrickLJH** [comment]
Describe the work done in detail.
Write the Pseudocode, Control Flow Graph, and Cyclomatic Complexity. Basis Path testing and test cases for Job allocation

Has this work been committed to the repo?
yes

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 16 Nov 2023 to 21 Nov 2023
