### ISSUE TITLE
2.2.1.2 Control Classes

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#64]
### Task title ID: 2.2.1.2 Control Classes #64
**Task Description** 
Refine and design control classes, specifying their data structures and algorithms.
 
**Goals of the Task**
To provide a comprehensive and unambiguous blueprint for the developers to follow during the development phase.

**Completion criteria**
- All control classes' data structures and algorithms are clearly defined.
- All control classes' designs have been evaluated and optimized.
- All control classes have been communicated to the development team.

**Allocated Time:** 4 Days
**Start/End Date:** 29 Sep 2023 - 3 Oct 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Designed each control class according to their methods and data structure. Each control class has a purpose and is connected to each other in the class diagram.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
NA.

Start date and end date of the work done for this comment.
Start/End Date: 29 Sep 2023 - 3 Oct 2023
