### ISSUE TITLE
2.2.1.3 Entity Classes

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#65]
### Task title ID: 2.2.1.3 Entity Classes #65
**Task Description** 
Refine and design entity classes, specifying their data structures and algorithms.
 
**Goals of the Task**
To provide a comprehensive and unambiguous blueprint for the developers to follow during the development phase.

**Completion criteria**
- All entity classes' data structures and algorithms are clearly defined.
- All entity classes' designs have been evaluated and optimized.
- All entity classes have been communicated to the development team.

**Allocated Time:** 4 Days
**Start/End Date:** 2 Oct 2023 - 6 Oct 2023
**Owner:** Cheryl
**Status:** Completed
**Priority:** High

**Comment by cherylthy** [comment]
Describe the work done in detail.
Completed entity classes structure and design in diagrams.net
Completed designing and visualizing individual entity classes for each system component. Attributes, methods, access levels, and object-oriented relationships were clearly defined. The entity classes were thoroughly evaluated.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 26 Aug 2023 - 28 Oct 2023
