### ISSUE TITLE
2.2.2.1 Sequence 1

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#67]
### Task title ID: 2.2.2.1 Sequence 1 #67
**Task Description** 
Illustrate the interactions and flow of messages between components over time for the first selected functionality of the system.
 
**Goals of the Task**
- To evaluate and ensure that system design meets specified requirements.
- To aid in designing test cases for validating system behavior.

**Completion criteria**
- All functionality flows for the selected use case are clearly illustrated and defined.
- All functionality flows for the selected use case are evaluated and validated.

**Allocated Time:** 4 Days
**Start/End Date:** 16 Oct 2023 - 20 Oct 2023
**Owner:** Isaac
**Status:** Completed
**Priority:** High

**Comment by RamenBoy0** [comment]
Describe the work done in detail.
Created the sequence diagram for leave management using diagrams.net, which includes the detailed visualization of each process within the system.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 16 Oct 2023 - 20 Oct 2023
