### ISSUE TITLE
2.2.2.2 Sequence 2

### ISSUE THREAD

**Issue by wongyufei1** [wongyufei1/INF2001_P3-2#68]
### Task title ID: 2.2.2.2 Sequence 2 #68
**Task Description** 
Illustrate the interactions and flow of messages between components over time for the second selected functionality of the system.
 
**Goals of the Task**
- To evaluate and ensure that system design meets specified requirements.
- To aid in designing test cases for validating system behavior.

**Completion criteria**
- All functionality flows for the selected use case are clearly illustrated and defined.
- All functionality flows for the selected use case are evaluated and validated.

**Allocated Time:** 4 Days
**Start/End Date:** 23 Oct 2023 - 27 Oct 2023
**Owner:** Cheryl
**Status:** Completed
**Priority:** High

**Comment by cherylthy** [comment]
Describe the work done in detail.
Completed sequence diagram for job allocation in diagrams.net
Completed designing and visualizing individual processes of the sequence diagram. Ensured that the methods used and the relationship between each entity, control, and boundary classes were depicted accurately.

Has this work been committed to the repo?
NA.

How does the work affect the completion deadline?
NA.

Are there any changes to the success or completion criteria of the task? If
yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start/End Date: 26 Aug 2023 - 28 Oct 2023
